name:                muck
version:             0.1.0.0
github:              "proaralyst/muck"
license:             BSD3
author:              "Tom Johnson"
maintainer:          "public@tomjohnson.me.uk"
copyright:           "2018 Tom Johnson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/proaralyst/muck#readme>

dependencies:
- base          >= 4.7 && < 5
- lens          == 4.16.1
- free          == 5.0.1
- text          == 1.2.3.0
- safe          == 0.3.17
- mtl           == 2.2.2
- free          == 5.0.1
- unix          == 2.7.2.2
- process       == 1.6.1.0
- conduit       == 1.3.0.2
- conduit-extra == 1.3.0
- bytestring    == 0.10.8.2

ghc-opts:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- TemplateHaskell
- DeriveFunctor
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  muck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - muck

tests:
  muck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - muck
